// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grading_tab.infrastructure;

#nullable disable

namespace grading_tab.infrastructure.Migrations
{
    [DbContext(typeof(GradingTabContext))]
    partial class GradingTabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grading_tab.domain.AggregateModels.AssessmentAggregate.AssessmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("assessment_type", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Attendance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Participation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Assignment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Project - Completion"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Project - Delivery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Major Exam"
                        });
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.AssessmentAggregate.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("term", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PRELIM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MIDTERM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PRE-FINAL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FINAL"
                        });
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.AssessmentResultAggregate.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssessmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<Guid>("_studentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentId");

                    b.Property<int>("_subjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<int>("_termId")
                        .HasColumnType("int")
                        .HasColumnName("TermId");

                    b.Property<int>("_typeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("_studentId");

                    b.HasIndex("_subjectId");

                    b.HasIndex("_termId");

                    b.HasIndex("_typeId");

                    b.ToTable("assessment_result", "dbo");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.PersonAggregate.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("person", "dbo");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SectionAggregate.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("section", "dbo");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SectionAggregate.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_personId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SectionId");

                    b.HasIndex("_personId");

                    b.ToTable("student", "dbo", t =>
                        {
                            t.Property("PersonId")
                                .HasColumnName("PersonId1");
                        });
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubjectLoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_typeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectLoadId");

                    b.HasIndex("_typeId");

                    b.ToTable("meeting", "dbo");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.MeetingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meeting_type", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASYNCHRONOUS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ON-SITE"
                        });
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subject", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CE ELECTIVE 2"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT ELECTIVE 3"
                        });
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.SubjectLoad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_facultyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacultyId");

                    b.Property<Guid>("_sectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SectionId");

                    b.Property<int>("_subjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("_facultyId");

                    b.HasIndex("_sectionId");

                    b.HasIndex("_subjectId");

                    b.ToTable("subject_load", "dbo");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.AssessmentResultAggregate.AssessmentResult", b =>
                {
                    b.HasOne("grading_tab.domain.AggregateModels.PersonAggregate.Person", "Student")
                        .WithMany()
                        .HasForeignKey("_studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.SubjectLoadAggregate.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("_subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.AssessmentAggregate.Term", "Term")
                        .WithMany()
                        .HasForeignKey("_termId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.AssessmentAggregate.AssessmentType", "Type")
                        .WithMany()
                        .HasForeignKey("_typeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SectionAggregate.Student", b =>
                {
                    b.HasOne("grading_tab.domain.AggregateModels.PersonAggregate.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.SectionAggregate.Section", null)
                        .WithMany("Students")
                        .HasForeignKey("SectionId");

                    b.HasOne("grading_tab.domain.AggregateModels.PersonAggregate.Person", null)
                        .WithMany()
                        .HasForeignKey("_personId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.Meeting", b =>
                {
                    b.HasOne("grading_tab.domain.AggregateModels.SubjectLoadAggregate.SubjectLoad", null)
                        .WithMany("Meetings")
                        .HasForeignKey("SubjectLoadId");

                    b.HasOne("grading_tab.domain.AggregateModels.SubjectLoadAggregate.MeetingType", "Type")
                        .WithMany()
                        .HasForeignKey("_typeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.SubjectLoad", b =>
                {
                    b.HasOne("grading_tab.domain.AggregateModels.PersonAggregate.Person", "Faculty")
                        .WithMany()
                        .HasForeignKey("_facultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.SectionAggregate.Section", "Section")
                        .WithMany()
                        .HasForeignKey("_sectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grading_tab.domain.AggregateModels.SubjectLoadAggregate.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("_subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SectionAggregate.Section", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("grading_tab.domain.AggregateModels.SubjectLoadAggregate.SubjectLoad", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
